apiVersion: apps/v1  # Requires v1.9+ K8s node versions
kind: Deployment
metadata:
  name: {{ include "wfl.fullname" . }}
  labels:
    {{- include "wfl.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wfl.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.strategy.maxSurge }}
      maxUnavailable: {{ .Values.strategy.maxUnavailable }}
  template:
    metadata:
      labels:
        {{- include "wfl.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "wfl.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.api.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          env:
          {{- if .Values.api.env }}
          {{- range $key, $value := .Values.api.env }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
          {{- end }}
          {{- end }}
          ports:
          - name: http
            containerPort: {{ .Values.api.deployment.containerPort }}
            protocol: TCP
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          volumeMounts:
            - name: service-account
              mountPath: {{ .Values.api.secrets.volumeMountPath }}
              subPath: service-account.json
        - name: {{ .Values.ui.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
          - name: http
            containerPort: {{ .Values.ui.deployment.containerPort }}
            protocol: TCP
          livenessProbe:
{{ toYaml .Values.ui.deployment.livenessProbe | indent 12 }}
          readinessProbe:
{{ toYaml .Values.ui.deployment.readinessProbe | indent 12 }}
          resources:
{{- toYaml .Values.ui.resources | nindent 12 }}
          env:
          {{- if .Values.ui.env }}
          {{- range $key, $value := .Values.ui.env }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
          {{- end }}
          {{- end }}
          volumeMounts:
            - mountPath: /etc/apache2/sites-available/site.conf
              name: siteconf
              subPath: site.conf
      volumes:
        - name: siteconf
          configMap:
            name: {{ template "wfl.fullname" . }}
            items:
              - key: siteconf
                path: site.conf
        - name: service-account
          secret:
            secretName: {{ template "wfl.fullname" . }}
            items:
              - key: service-account
                path: service-account.json

