apiVersion: apps/v1  # Requires v1.9+ K8s node versions
kind: Deployment
metadata:
  name: {{ include "wfl.fullname" . }}
  labels:
    {{- include "wfl.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wfl.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.strategy.maxSurge }}
      maxUnavailable: {{ .Values.strategy.maxUnavailable }}
  template:
    metadata:
      labels:
        {{- include "wfl.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "wfl.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.api.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
          - name: http
            containerPort: {{ .Values.api.deployment.containerPort }}
            protocol: TCP
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
        - name: {{ .Values.ui.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
          - name: http
            containerPort: {{ .Values.ui.deployment.containerPort }}
            protocol: TCP
          livenessProbe:
            httpGet:
              scheme: {{ .Values.ui.deployment.livenessProbe.scheme }}
              path: {{ .Values.ui.deployment.livenessProbe.path }}
              port: {{ .Values.ui.deployment.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.ui.deployment.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.ui.deployment.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.ui.deployment.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.ui.deployment.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              scheme: {{ .Values.ui.deployment.readinessProbe.scheme }}
              path: {{ .Values.ui.deployment.readinessProbe.path }}
              port: {{ .Values.ui.deployment.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.ui.deployment.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.ui.deployment.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.ui.deployment.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.ui.deployment.readinessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
          env:
            - name: SERVER_NAME
              value: {{ .Values.ui.env.SERVER_NAME | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.ui.env.LOG_LEVEL | quote }}
            - name: AUTH_TYPE
              value: {{ .Values.ui.env.AUTH_TYPE | quote }}
            - name: AUTH_TYPE2
              value: {{ .Values.ui.env.AUTH_TYPE2 | quote }}
            - name: AUTH_REQUIRE
              value: {{ .Values.ui.env.AUTH_REQUIRE | quote }}
            - name: AUTH_REQUIRE2
              value: {{ .Values.ui.env.AUTH_REQUIRE2 | quote }}
            - name: PROXY_URL
              value: {{ .Values.ui.env.PROXY_URL | quote }}
            - name: PROXY_URL2
              value: {{ .Values.ui.env.PROXY_URL2 | quote }}
            - name: ENABLE_STACKDRIVER
              value: {{ .Values.ui.env.ENABLE_STACKDRIVER | quote }}
            - name: ENABLE_REMOTEIP
              value: {{ .Values.ui.env.ENABLE_REMOTEIP | quote }}
            - name: REMOTE_USER_CLAIM
              value: {{ .Values.ui.env.REMOTE_USER_CLAIM | quote }}
            - name: CALLBACK_URI
              value: {{ .Values.ui.env.CALLBACK_URI | quote }}
            - name: FILTER2
              value: {{ .Values.ui.env.FILTER2 | quote }}
            - name: FILTER
              value: {{ .Values.ui.env.FILTER | quote }}
            - name: PROXY_PATH
              value: {{ .Values.ui.env.PROXY_PATH | quote }}
            - name: PROXY_PATH2
              value: {{ .Values.ui.env.PROXY_PATH2 | quote }}
          volumeMounts:
            - mountPath: /etc/apache2/sites-available/site.conf
              name: siteconf
              subPath: site.conf
      volumes:
        - name: siteconf
          configMap:
            name: {{ template "wfl.fullname" . }}
            items:
              - key: siteconf
                path: site.conf
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
