{{- if .Values.ingress.enabled -}}

{{- $fullName := include "wfl.fullname" . -}}
{{- $servicePort := .Values.ingress.servicePort -}}

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ $fullName }}-backend-config
spec:
  timeoutSec: {{ .Values.ingress.backendTimeout }}

---

{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "wfl.labels" . | nindent 4 }}
{{- with .Values.ingress.annotations }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ $fullName }}-backend-config"}'
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- $paths := default (list "/") .paths }}
        {{- range $paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
        {{- end }}
  {{- end }}

{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end }}
{{- end }}
