{{- if .Values.rbac.create }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: "{{ include "wfl.fullname" . }}-pod-running-policy"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wfl.labels" . | nindent 4 }}
    name: podsecuritypolicy
spec:
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
    - '*'
  {{- end }}
