{{- if .Values.rbac.create -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ include "wfl.fullname" . }}-use-pod-security-policy"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wfl.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "wfl.serviceAccountName" . }}
roleRef:
  kind: Role
  name: "{{ include "wfl.fullname" . }}-use-pod-security-policy-role"
  apiGroup: rbac.authorization.k8s.io
  {{- end }}
