{{- if .Values.api.secrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "wfl.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "wfl.labels" . | nindent 4 }}
stringData:
  service-account: |-
{{ .Values.api.secrets.secretsgeneric.serivceAccountCredentialFileJSON | indent 4 }}
{{/*{{ .Files.Get "service-account.json" | indent 4}}*/}}
{{- end }}
