# Shell functions
AWK     := awk
BOOT    := boot
CAT     := cat
CD      := cd
CLOJURE := clojure
CP      := cp
DOCKER  := docker
ECHO    := echo
EXPORT  := export
FIND    := find
GIT     := git
GREP    := grep
JAVA    := java
JQ      := jq
LEIN    := lein
LN 	    := ln -s
MKDIR   := mkdir -p
MV      := mv -f
PUSHD   := pushd
POPD    := popd
PR      := pr
SED     := sed
SORT    := sort
TOUCH   := touch
