# Shell functions
AWK     := awk
BOOT    := boot
CAT     := cat
CD      := cd
CLOJURE := clojure
CP      := cp -f
DOCKER  := docker
ECHO    := echo
EXPORT  := export
FIND    := find
GIT     := git
GREP    := grep
JAVA    := java
JQ      := jq
LEIN    := lein
LN 	    := ln -s
MKDIR   := mkdir -p
MV      := mv -f
NPM     := npm
POPD    := popd
PUSHD   := pushd
PYTHON  := python3
PR      := pr
SED     := sed
SOURCE  := source
SORT    := sort
TEE     := tee
TOUCH   := touch
