# Module targets

ifndef MODULE
$(error MODULE was not defined - please invoke make from top level)
endif

# Directories
PROJECT_DIR         ?= $(shell dirname $(CURDIR))
MODULE_DIR          := $(PROJECT_DIR)/$(MODULE)
DERIVED_DIR         ?= $(PROJECT_DIR)/derived
THIRD_PARTY_DIR     := $(DERIVED_DIR)/3p
DERIVED_MODULE_DIR  := $(DERIVED_DIR)/$(MODULE)
export WFL_VERSION	?= $(shell $(CAT) $(PROJECT_DIR)/version)

# Top level `make` targets for the module
MAKE_TARGETS := prebuild build check images

# Timestamps for the top level make targets.
# Write your module make-targets against these
PREBUILD := $(DERIVED_MODULE_DIR)/prebuild.$(TS)
BUILD    := $(DERIVED_MODULE_DIR)/build.$(TS)
CHECK    := $(DERIVED_MODULE_DIR)/check.$(TS)
IMAGES   := $(DERIVED_MODULE_DIR)/images.$(TS)

.PHONY:	all $(MAKE_TARGETS)
all: $(MAKE_TARGETS)
$(MAKE_TARGETS): | $(DERIVED_MODULE_DIR)

# `make` target dependencies
prebuild:
build:    prebuild
check:    build
images:   build

# Top level `make` targets depend on their corresponding timestamp.
# We use a pattern instead of the actual to allow module.mk to override
# the default recipe.
$(MAKE_TARGETS): % : $(DERIVED_MODULE_DIR)/%.$(TS)
$(DERIVED_MODULE_DIR)/%.$(TS):
	@$(TOUCH) $@

CLEAN_DIRS    := $(DERIVED_MODULE_DIR)
CLEAN_FILES   :=
.PHONY:	clean
clean:
	$(RM) -r $(CLEAN_DIRS)
	$(RM) $(CLEAN_FILES)

define invoke
  $(MAKE) -f $(firstword $(MAKEFILE_LIST))
endef

.PHONY: help
help:
	@$(invoke) --print-data-base --question no-such-target | \
		$(GREP) -v -e '^no-such-target' -e '^Makefile' |   \
		$(AWK) '/^[^.%][-A-Za-z0-9_]*:/                    \
		    { print substr($$1, 1, length($$1)-1) }' |     \
		$(SORT) |                                          \
		$(PR) --omit-pagination --width=80 --columns=4     \

$(DERIVED_DIR) $(THIRD_PARTY_DIR) $(DERIVED_MODULE_DIR):
	@$(MKDIR) $@

# 3p Repositories
THIRD_PARTY_REPOSITORIES := \
  $(patsubst %, $(THIRD_PARTY_DIR)/%.$(TS),$(REQUIRED_GITHUB_REPOSITORIES))

define make-github-url
  $(patsubst $(THIRD_PARTY_DIR)/%.$(TS),git@github.com:%.git,$@)
endef

$(PREBUILD): $(THIRD_PARTY_REPOSITORIES)
$(THIRD_PARTY_REPOSITORIES): $(THIRD_PARTY_DIR)
	$(GIT) clone $(make-github-url) $(patsubst %.$(TS),%,$@)
	@$(TOUCH) $@
