site_name: Workflow Launcher

repo_url: https://github.com/broadinstitute/wfl

theme:
  name: material
  palette:
   primary: green
   accent: teal
  feature:
    tabs: true

docs_dir: "md"

extra:
  version: 2.0
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/broadinstitute/wfl'

nav:
  - Get Started:
    - README.md
  - Modules:
    - Arrays: module-arrays.md
  - Deployment:
    - Deployment with Kubernetes: deployment.md
    - Making your sandbox: sandbox.md
  - Frontend:
    - Frontend: frontend.md
  - Server:
    - Server: server.md
  - Readings:
    - Development Process: dev-process.md
    - Logging: logging.md
    - WorkFlow Launcher's Role in Terra: terra.md

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: True
  - markdown_include.include:
      base_path: md
