site_name: Workflow Launcher

repo_url: https://github.com/broadinstitute/wfl

theme:
  name: material
  palette:
    - scheme: default
      primary: green
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  feature:
    tabs: true

docs_dir: "md"

extra:
  version: 2.0
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/broadinstitute/wfl'

nav:
  - Get Started: index.md
  - Development Guide:
    - Development Process and Tips: dev-process.md
    - Release Process: dev-release.md
    - Local Development SandBox: dev-sandbox.md
    - Logging: dev-logging.md
    - Deployment: dev-deployment.md
    - Frontend: dev-frontend.md
  - Modules:
    - General: modules-general.md
    - Workflow Options: workflow-options.md
    - Arrays: modules-arrays.md
    - Whole Genome: modules-wgs.md
    - External Exome: modules-external-exome-reprocessing.md
  - Readings:
    - WorkFlow Launcher's Role in Terra: terra.md

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: ⚓︎
  - markdown_include.include:
      base_path: md
