site_name: Workflow Launcher

repo_url: https://github.com/broadinstitute/wfl

theme:
  name: material
  palette:
   primary: green
   accent: teal
  feature:
    tabs: true

docs_dir: "md"

extra:
  version: 2.0
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/broadinstitute/wfl'

nav:
  - Get Started: README.md
  - Development Guide:
    - Clojure Development: dev-clojure.md
    - Local Development SandBox: dev-sandbox.md
    - Development Process: dev-process.md
    - Logging: dev-logging.md
    - Deployment: dev-deployment.md
    - Frontend: dev-frontend.md
  - Modules:
    - General: modules-general.md
    - Arrays: modules-arrays.md
  - Readings:
    - WorkFlow Launcher's Role in Terra: terra.md

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: True
  - markdown_include.include:
      base_path: md
