# This is a basic workflow to help you get started with Actions
# Deployment keys for this gitaction may be found at secret/dsde/gotc/dev/ci/wfl_deploy_keys

name: Build and Publish Docker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      MODULES: api ui

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Get Branch Name
      id: get_branch
      shell: bash
      run: |
        BRANCH_NAME=$(echo ${GITHUB_HEAD_REF#refs/heads/})
        if [ -z "${BRANCH_NAME}" ]
        then
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
        fi
        echo "##[set-output name=BRANCH_NAME;]$(echo ${BRANCH_NAME})"

    - name: Install Clojure tools
      uses: DeLaGuardo/setup-clojure@2.0
      with:
        boot: 2.8.3

        - name: Configure SSH Keys
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.dsde_pipelines_deploy_key }}" > ~/.ssh/dsde_pipelines_deploy_key
          echo "${{ secrets.pipeline_config_deploy_key }}" > ~/.ssh/pipeline_config_deploy_key
          echo "${{ secrets.wfl_deploy_key }}" > ~/.ssh/wfl_deploy_key

          chmod 600 ~/.ssh/dsde_pipelines_deploy_key
          chmod 600 ~/.ssh/pipeline_config_deploy_key
          chmod 600 ~/.ssh/wfl_deploy_key

          echo """
            Host dsde-pipelines.github.com
            HostName github.com
            User git
            IdentityFile ~/.ssh/dsde_pipelines_deploy_key

            Host pipeline-config.github.com
            HostName github.com
            User git
            IdentityFile ~/.ssh/pipeline_config_deploy_key

            Host wfl.github.com
            HostName github.com
            User git
            IdentityFile ~/.ssh/wfl_deploy_key """ > ~/.ssh/config

      - name: Pre-Build
        run: make "${MODULES}" TARGET=prebuild

      - name: Build
        run: make "${MODULES}" TARGET=build

    - name: Build and Publish Docker Images
      run: |
        BASE_VERSION=$(cat version)
        echo $BASE_VERSION

        if [[ ${{ steps.get_branch.outputs.BRANCH_NAME }} == "master" ]]
        then
          VERSION="${BASE_VERSION}"
        else
          VERSION="${BASE_VERSION}-${{ steps.get_branch.outputs.BRANCH_NAME }}"
        fi

        # Build the images
        export WFL_VERSION="${VERSION}" && make "${MODULES}" TARGET=images

        # Tag the images
        docker tag \
            "broadinstitute/workflow-launcher-api:${VERSION}" \
            broadinstitute/workflow-launcher-api:latest
        docker tag \
            "broadinstitute/workflow-launcher-ui:${VERSION}" \
            broadinstitute/workflow-launcher-ui:latest

        # Publish the Images
        docker login \
          --username "${{ secrets.dockerhub_username }}" \
          --password "${{ secrets.dockerhub_password }}"

        docker push "broadinstitute/workflow-launcher-api:${VERSION}"
        docker push broadinstitute/workflow-launcher-api:latest

        docker push "broadinstitute/workflow-launcher-ui:${VERSION}"
        docker push broadinstitute/workflow-launcher-ui:latest
