name: Helm Charts Release

on:
  push:
    branches:
      - master
    paths:
      - helm/**

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: '2'
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - name: Run chart-releaser
      uses: broadinstitute/chart-releaser-action@v1.0.0-rc.3
      env:
        CR_TOKEN: "${{ secrets.CR_TOKEN }}"
      with:
        charts_dir: "helm"
        charts_repo: "gotc-helm-repo"
