# This workflow triggers helm linting on PRs and master branch pushes
# that affect helm files
name: Helm Chart Linting on Pull Requests and Master

on:
  push:
    branches:
      - master
    paths:
      - 'helm/wfl/**'
  pull_request:
    paths:
      - 'helm/wfl/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: quay.io/helmpack/chart-testing:v3.0.0-rc.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Helm Chart Strict Lint
        working-directory: './helm/wfl'
        run: |
          helm lint --strict --namespace default
          yamale --schema /etc/ct/chart_schema.yaml Chart.yaml
          yamllint --config-file /etc/ct/lintconf.yaml --strict Chart.yaml values.yaml
