# This workflow triggers helm linting on PRs and master branch pushes
# that affect helm files
name: Helm Chart Linting on Pull Requests and Master

on:
  push:
    branches:
      - master
    paths:
      - 'helm/**'
  pull_request:
    paths:
      - 'helm/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Helm Chart Lint
        uses: helm/chart-testing-action@v1.0.0-rc.1
        with:
          command: lint
          config: ct.yaml
