# This workflow triggers helm linting on PRs and master branch pushes
# that affect helm files
name: Helm Chart Linting on Pull Requests and Master

on:
  push:
    branches:
      - master
    paths:
      - helm/wfl/**
  pull_request:
    paths:
      - helm/wfl/**

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: quay.io/helmpack/chart-testing:v3.0.0-rc.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

        # `ct lint` likes to find charts on its own using git
        # history.
      - name: Fetch History
        run: git fetch --prune --unshallow

        # We keep this around because it does version bump and
        # maintenance checks outside of what `helm lint` does.
        # It is separate because it needs to be at the top of
        # the repo.
      - name: Chart Test Basic Lint
        run: ct lint --config ct.yaml

      - name: Helm Chart Strict Lint
        working-directory: ./helm/wfl
        run: |
          helm lint --strict --namespace default
          yamale --schema /etc/ct/chart_schema.yaml Chart.yaml
          yamllint --config-file /etc/ct/lintconf.yaml --strict Chart.yaml values.yaml

      # We could theoretically run `ct install` or
      # something else here, but there were breadcrumbs
      # in previous Helm lint actions that installing
      # fails on hyphenated names, so more work would
      # need to be done to eliminate hyphens from
      # generated names
